# Generated by Django 6.0.3 on 2026-03-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="todo_images/"),
        ),
    ]
